logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
spring:
  application:
    name: gateway-service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888}