logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
spring:
  application:
    name: gateway-service
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials RETAIN_FIRST
